In [6]:
import numpy as np
import pandas as pd
import math as m

In [7]:
df = pd.read_csv("D:\\CUDA_ENV\\Bleep_B1\\2_Data_Handling_Tools\\Pandas\\Data\\tips.csv")
df

     total_bill   tip     sex smoker   day    time  size  price_per_person
0         16.99  1.01  Female     No   Sun  Dinner     2              8.49
1         10.34  1.66    Male     No   Sun  Dinner     3              3.45
2         21.01  3.50    Male     No   Sun  Dinner     3              7.00
3         23.68  3.31    Male     No   Sun  Dinner     2             11.84
4         24.59  3.61  Female     No   Sun  Dinner     4              6.15
..          ...   ...     ...    ...   ...     ...   ...               ...
239       29.03  5.92    Male     No   Sat  Dinner     3              9.68
240       27.18  2.00  Female    Yes   Sat  Dinner     2             13.59
241       22.67  2.00    Male    Yes   Sat  Dinner     2             11.34
242       17.82  1.75    Male     No   Sat  Dinner     2              8.91
243       18.78  3.00  Female     No  Thur  Dinner     2              9.39

[244 rows x 8 columns]

In [8]:
df.shape

(244, 8)

In [9]:
df.columns

Index(['total_bill', 'tip', 'sex', 'smoker', 'day', 'time', 'size',
       'price_per_person'],
      dtype='str')

In [10]:
type(df.columns)

pandas.Index

In [13]:
df.loc[0]

total_bill           16.99
tip                   1.01
sex                 Female
smoker                  No
day                    Sun
time                Dinner
size                     2
price_per_person      8.49
Name: 0, dtype: object

In [15]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 244 entries, 0 to 243
Data columns (total 8 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   total_bill        244 non-null    float64
 1   tip               244 non-null    float64
 2   sex               244 non-null    str
 3   smoker            244 non-null    str
 4   day               244 non-null    str
 5   time              244 non-null    str
 6   size              244 non-null    int64
 7   price_per_person  244 non-null    float64
dtypes: float64(3), int64(1), str(4)
memory usage: 15.4 KB

In [16]:
df.describe()

       total_bill         tip        size  price_per_person
count  244.000000  244.000000  244.000000        244.000000
mean    19.785943    2.998279    2.569672          7.888197
std      8.902412    1.383638    0.951100          2.914234
min      3.070000    1.000000    1.000000          2.880000
25%     13.347500    2.000000    2.000000          5.800000
50%     17.795000    2.900000    2.000000          7.255000
75%     24.127500    3.562500    3.000000          9.390000
max     50.810000   10.000000    6.000000         20.270000

In [17]:
df.describe().transpose()

,count,mean,std,min,25%,50%,75%,max
total_bill,244.0,19.785943,8.902412,3.07,13.3475,17.795,24.1275,50.81
tip,244.0,2.998279,1.383638,1.00,2.0000,2.900,3.5625,10.00
size,244.0,2.569672,0.951100,1.00,2.0000,2.000,3.0000,6.00
price_per_person,244.0,7.888197,2.914234,2.88,5.8000,7.255,9.3900,20.27

In [18]:
df

     total_bill   tip     sex smoker   day    time  size  price_per_person
0         16.99  1.01  Female     No   Sun  Dinner     2              8.49
1         10.34  1.66    Male     No   Sun  Dinner     3              3.45
2         21.01  3.50    Male     No   Sun  Dinner     3              7.00
3         23.68  3.31    Male     No   Sun  Dinner     2             11.84
4         24.59  3.61  Female     No   Sun  Dinner     4              6.15
..          ...   ...     ...    ...   ...     ...   ...               ...
239       29.03  5.92    Male     No   Sat  Dinner     3              9.68
240       27.18  2.00  Female    Yes   Sat  Dinner     2             13.59
241       22.67  2.00    Male    Yes   Sat  Dinner     2             11.34
242       17.82  1.75    Male     No   Sat  Dinner     2              8.91
243       18.78  3.00  Female     No  Thur  Dinner     2              9.39

[244 rows x 8 columns]

In [22]:
# I want to create a new column 

# tip_percentage = 100*(tip / total_bill )

type(df['tip'])

df['tip_percentage'] = 100 * (df['tip'] / df ['total_bill'])

df['tip_percentage'] = np.round(100 * (df['tip'] / df ['total_bill']),2)
df

,total_bill,tip,sex,smoker,day,time,size,price_per_person,tip_percentage
0,16.99,1.01,Female,No,Sun,Dinner,2,8.49,5.94
1,10.34,1.66,Male,No,Sun,Dinner,3,3.45,16.05
2,21.01,3.50,Male,No,Sun,Dinner,3,7.00,16.66
3,23.68,3.31,Male,No,Sun,Dinner,2,11.84,13.98
4,24.59,3.61,Female,No,Sun,Dinner,4,6.15,14.68
...,...,...,...,...,...,...,...,...,...
239,29.03,5.92,Male,No,Sat,Dinner,3,9.68,20.39
240,27.18,2.00,Female,Yes,Sat,Dinner,2,13.59,7.36
241,22.67,2.00,Male,Yes,Sat,Dinner,2,11.34,8.82
242,17.82,1.75,Male,No,Sat,Dinner,2,8.91,9.82
243,18.78,3.00,Female,No,Thur,Dinner,2,9.39,15.97

In [26]:
# what is the maximum and minimum part size that ever ate at the resturant

df['size'].idxmax()

125

In [27]:
df.loc[125]

total_bill            29.8
tip                    4.2
sex                 Female
smoker                  No
day                   Thur
time                 Lunch
size                     6
price_per_person      4.97
tip_percentage       14.09
Name: 125, dtype: object

In [31]:
#minimum part size

df['size'].min()
print(df['size'].idxmin())

67

In [32]:
df.loc[df['size'].idxmin()]

total_bill            3.07
tip                    1.0
sex                 Female
smoker                 Yes
day                    Sat
time                Dinner
size                     1
price_per_person      3.07
tip_percentage       32.57
Name: 67, dtype: object

In [33]:
## Conditional Statements

In [34]:
df

,total_bill,tip,sex,smoker,day,time,size,price_per_person,tip_percentage
0,16.99,1.01,Female,No,Sun,Dinner,2,8.49,5.94
1,10.34,1.66,Male,No,Sun,Dinner,3,3.45,16.05
2,21.01,3.50,Male,No,Sun,Dinner,3,7.00,16.66
3,23.68,3.31,Male,No,Sun,Dinner,2,11.84,13.98
4,24.59,3.61,Female,No,Sun,Dinner,4,6.15,14.68
...,...,...,...,...,...,...,...,...,...
239,29.03,5.92,Male,No,Sat,Dinner,3,9.68,20.39
240,27.18,2.00,Female,Yes,Sat,Dinner,2,13.59,7.36
241,22.67,2.00,Male,Yes,Sat,Dinner,2,11.34,8.82
242,17.82,1.75,Male,No,Sat,Dinner,2,8.91,9.82
243,18.78,3.00,Female,No,Thur,Dinner,2,9.39,15.97

In [37]:
df['time'].unique()

<StringArray>
['Dinner', 'Lunch']
Length: 2, dtype: str

In [ ]:
# How many people are smoker ?
df['smoker']

0       No
1       No
2       No
3       No
4       No
      ...
239     No
240    Yes
241    Yes
242     No
243     No
Name: smoker, Length: 244, dtype: str

In [40]:
df['smoker'] == "Yes"    # Boolean Series

print(type(df['smoker'] == "Yes"  ))

<class 'pandas.Series'>

In [42]:
smokers_df = df[df['smoker'] == "Yes"]
smokers_df

,total_bill,tip,sex,smoker,day,time,size,price_per_person,tip_percentage
56,38.01,3.00,Male,Yes,Sat,Dinner,4,9.50,7.89
58,11.24,1.76,Male,Yes,Sat,Dinner,2,5.62,15.66
60,20.29,3.21,Male,Yes,Sat,Dinner,2,10.14,15.82
61,13.81,2.00,Male,Yes,Sat,Dinner,2,6.90,14.48
62,11.02,1.98,Male,Yes,Sat,Dinner,2,5.51,17.97
...,...,...,...,...,...,...,...,...,...
234,15.53,3.00,Male,Yes,Sat,Dinner,2,7.76,19.32
236,12.60,1.00,Male,Yes,Sat,Dinner,2,6.30,7.94
237,32.83,1.17,Male,Yes,Sat,Dinner,2,16.42,3.56
240,27.18,2.00,Female,Yes,Sat,Dinner,2,13.59,7.36
241,22.67,2.00,Male,Yes,Sat,Dinner,2,11.34,8.82

In [43]:
print("Total Number of Smokers", len(smokers_df))

Total Number of Smokers 93

In [44]:
# Conditional Filtering

In [56]:
# And : & 

# OR : | 

len(df[(df['smoker'] == "Yes" ) & (df['sex']== "Male")])
df[(df['smoker'] == "Yes" ) & (df['sex']== "Male") & (df['size'] > 2)]

,total_bill,tip,sex,smoker,day,time,size,price_per_person,tip_percentage
56,38.01,3.00,Male,Yes,Sat,Dinner,4,9.50,7.89
63,18.29,3.76,Male,Yes,Sat,Dinner,4,4.57,20.56
95,40.17,4.73,Male,Yes,Fri,Dinner,4,10.04,11.77
170,50.81,10.00,Male,Yes,Sat,Dinner,3,16.94,19.68
180,34.65,3.68,Male,Yes,Sun,Dinner,4,8.66,10.62
182,45.35,3.50,Male,Yes,Sun,Dinner,3,15.12,7.72
183,23.17,6.50,Male,Yes,Sun,Dinner,4,5.79,28.05
187,30.46,2.00,Male,Yes,Sun,Dinner,5,6.09,6.57
189,23.10,4.00,Male,Yes,Sun,Dinner,3,7.70,17.32
200,18.71,4.00,Male,Yes,Thur,Lunch,3,6.24,21.38
204,20.53,4.00,Male,Yes,Thur,Lunch,4,5.13,19.48
206,26.59,3.41,Male,Yes,Sat,Dinner,3,8.86,12.82
207,38.73,3.00,Male,Yes,Sat,Dinner,4,9.68,7.75
210,30.06,2.00,Male,Yes,Sat,Dinner,3,10.02,6.65
211,25.89,5.16,Male,Yes,Sat,Dinner,4,6.47,19.93
216,28.15,3.00,Male,Yes,Sat,Dinner,5,5.63,10.66
230,24.01,2.00,Male,Yes,Sat,Dinner,4,6.00,8.33
231,15.69,3.00,Male,Yes,Sat,Dinner,3,5.23,19.12

In [48]:
len(df[(df['smoker'] == "Yes" ) & (df['sex']== "Female")])

33

In [50]:
# Total number of smokers who are smoking or sex is male

(df['smoker'] == "Yes" ) | (df['sex']== "Male")

0      False
1       True
2       True
3       True
4      False
       ...
239     True
240     True
241     True
242     True
243    False
Length: 244, dtype: bool

In [51]:
df[(df['smoker'] == "Yes" ) | (df['sex']== "Male")]

,total_bill,tip,sex,smoker,day,time,size,price_per_person,tip_percentage
1,10.34,1.66,Male,No,Sun,Dinner,3,3.45,16.05
2,21.01,3.50,Male,No,Sun,Dinner,3,7.00,16.66
3,23.68,3.31,Male,No,Sun,Dinner,2,11.84,13.98
5,25.29,4.71,Male,No,Sun,Dinner,4,6.32,18.62
6,8.77,2.00,Male,No,Sun,Dinner,2,4.38,22.81
...,...,...,...,...,...,...,...,...,...
237,32.83,1.17,Male,Yes,Sat,Dinner,2,16.42,3.56
239,29.03,5.92,Male,No,Sat,Dinner,3,9.68,20.39
240,27.18,2.00,Female,Yes,Sat,Dinner,2,13.59,7.36
241,22.67,2.00,Male,Yes,Sat,Dinner,2,11.34,8.82
242,17.82,1.75,Male,No,Sat,Dinner,2,8.91,9.82

In [52]:
df[(df['smoker'] == "Yes" ) | (df['sex']== "Female")]

,total_bill,tip,sex,smoker,day,time,size,price_per_person,tip_percentage
0,16.99,1.01,Female,No,Sun,Dinner,2,8.49,5.94
4,24.59,3.61,Female,No,Sun,Dinner,4,6.15,14.68
11,35.26,5.00,Female,No,Sun,Dinner,4,8.82,14.18
14,14.83,3.02,Female,No,Sun,Dinner,2,7.42,20.36
16,10.33,1.67,Female,No,Sun,Dinner,3,3.44,16.17
...,...,...,...,...,...,...,...,...,...
237,32.83,1.17,Male,Yes,Sat,Dinner,2,16.42,3.56
238,35.83,4.67,Female,No,Sat,Dinner,3,11.94,13.03
240,27.18,2.00,Female,Yes,Sat,Dinner,2,13.59,7.36
241,22.67,2.00,Male,Yes,Sat,Dinner,2,11.34,8.82
243,18.78,3.00,Female,No,Thur,Dinner,2,9.39,15.97

In [53]:
df[(df['smoker'] == "No" ) | (df['sex']== "Female")]

,total_bill,tip,sex,smoker,day,time,size,price_per_person,tip_percentage
0,16.99,1.01,Female,No,Sun,Dinner,2,8.49,5.94
1,10.34,1.66,Male,No,Sun,Dinner,3,3.45,16.05
2,21.01,3.50,Male,No,Sun,Dinner,3,7.00,16.66
3,23.68,3.31,Male,No,Sun,Dinner,2,11.84,13.98
4,24.59,3.61,Female,No,Sun,Dinner,4,6.15,14.68
...,...,...,...,...,...,...,...,...,...
238,35.83,4.67,Female,No,Sat,Dinner,3,11.94,13.03
239,29.03,5.92,Male,No,Sat,Dinner,3,9.68,20.39
240,27.18,2.00,Female,Yes,Sat,Dinner,2,13.59,7.36
242,17.82,1.75,Male,No,Sat,Dinner,2,8.91,9.82
243,18.78,3.00,Female,No,Thur,Dinner,2,9.39,15.97

In [57]:
df.columns

Index(['total_bill', 'tip', 'sex', 'smoker', 'day', 'time', 'size',
       'price_per_person', 'tip_percentage'],
      dtype='str')

In [59]:
# drop a column 

df = df.drop(['tip_percentage'],axis=1)
df

     total_bill   tip     sex smoker   day    time  size  price_per_person
0         16.99  1.01  Female     No   Sun  Dinner     2              8.49
1         10.34  1.66    Male     No   Sun  Dinner     3              3.45
2         21.01  3.50    Male     No   Sun  Dinner     3              7.00
3         23.68  3.31    Male     No   Sun  Dinner     2             11.84
4         24.59  3.61  Female     No   Sun  Dinner     4              6.15
..          ...   ...     ...    ...   ...     ...   ...               ...
239       29.03  5.92    Male     No   Sat  Dinner     3              9.68
240       27.18  2.00  Female    Yes   Sat  Dinner     2             13.59
241       22.67  2.00    Male    Yes   Sat  Dinner     2             11.34
242       17.82  1.75    Male     No   Sat  Dinner     2              8.91
243       18.78  3.00  Female     No  Thur  Dinner     2              9.39

[244 rows x 8 columns]

In [63]:
df = df.drop(['smoker'],axis=1)
df

     total_bill   tip     sex   day    time  size  price_per_person
0         16.99  1.01  Female   Sun  Dinner     2              8.49
1         10.34  1.66    Male   Sun  Dinner     3              3.45
2         21.01  3.50    Male   Sun  Dinner     3              7.00
3         23.68  3.31    Male   Sun  Dinner     2             11.84
4         24.59  3.61  Female   Sun  Dinner     4              6.15
..          ...   ...     ...   ...     ...   ...               ...
239       29.03  5.92    Male   Sat  Dinner     3              9.68
240       27.18  2.00  Female   Sat  Dinner     2             13.59
241       22.67  2.00    Male   Sat  Dinner     2             11.34
242       17.82  1.75    Male   Sat  Dinner     2              8.91
243       18.78  3.00  Female  Thur  Dinner     2              9.39

[244 rows x 7 columns]

In [66]:
df = pd.read_csv("D:\\CUDA_ENV\\Bleep_B1\\2_Data_Handling_Tools\\Pandas\\Data\\tips.csv")
df

     total_bill   tip     sex smoker   day    time  size  price_per_person
0         16.99  1.01  Female     No   Sun  Dinner     2              8.49
1         10.34  1.66    Male     No   Sun  Dinner     3              3.45
2         21.01  3.50    Male     No   Sun  Dinner     3              7.00
3         23.68  3.31    Male     No   Sun  Dinner     2             11.84
4         24.59  3.61  Female     No   Sun  Dinner     4              6.15
..          ...   ...     ...    ...   ...     ...   ...               ...
239       29.03  5.92    Male     No   Sat  Dinner     3              9.68
240       27.18  2.00  Female    Yes   Sat  Dinner     2             13.59
241       22.67  2.00    Male    Yes   Sat  Dinner     2             11.34
242       17.82  1.75    Male     No   Sat  Dinner     2              8.91
243       18.78  3.00  Female     No  Thur  Dinner     2              9.39

[244 rows x 8 columns]

In [65]:
df_copy = df.copy()

df_copy = df_copy.drop(['smoker'],axis=1)
df_copy

     total_bill   tip     sex   day    time  size  price_per_person
0         16.99  1.01  Female   Sun  Dinner     2              8.49
1         10.34  1.66    Male   Sun  Dinner     3              3.45
2         21.01  3.50    Male   Sun  Dinner     3              7.00
3         23.68  3.31    Male   Sun  Dinner     2             11.84
4         24.59  3.61  Female   Sun  Dinner     4              6.15
..          ...   ...     ...   ...     ...   ...               ...
239       29.03  5.92    Male   Sat  Dinner     3              9.68
240       27.18  2.00  Female   Sat  Dinner     2             13.59
241       22.67  2.00    Male   Sat  Dinner     2             11.34
242       17.82  1.75    Male   Sat  Dinner     2              8.91
243       18.78  3.00  Female  Thur  Dinner     2              9.39

[244 rows x 7 columns]

In [68]:


# Apply Method call


df.info()

<class 'pandas.DataFrame'>
RangeIndex: 244 entries, 0 to 243
Data columns (total 8 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   total_bill        244 non-null    float64
 1   tip               244 non-null    float64
 2   sex               244 non-null    str
 3   smoker            244 non-null    str
 4   day               244 non-null    str
 5   time              244 non-null    str
 6   size              244 non-null    int64
 7   price_per_person  244 non-null    float64
dtypes: float64(3), int64(1), str(4)
memory usage: 15.4 KB

In [69]:
def tip_percentage(tip: float, total_bill:float):
    tip_percentage = 100*(tip/total_bill)

In [74]:
def yelp(price : float):
    if price < 12 :
        return '$'
    elif price >=12 and price < 35 :
        return '$$'

    else :
        return '$$$'

In [75]:
df['Expensive'] = df['total_bill'].apply(yelp)
df

,total_bill,tip,sex,smoker,day,time,size,price_per_person,Expensive
0,16.99,1.01,Female,No,Sun,Dinner,2,8.49,$$
1,10.34,1.66,Male,No,Sun,Dinner,3,3.45,$
2,21.01,3.50,Male,No,Sun,Dinner,3,7.00,$$
3,23.68,3.31,Male,No,Sun,Dinner,2,11.84,$$
4,24.59,3.61,Female,No,Sun,Dinner,4,6.15,$$
...,...,...,...,...,...,...,...,...,...
239,29.03,5.92,Male,No,Sat,Dinner,3,9.68,$$
240,27.18,2.00,Female,Yes,Sat,Dinner,2,13.59,$$
241,22.67,2.00,Male,Yes,Sat,Dinner,2,11.34,$$
242,17.82,1.75,Male,No,Sat,Dinner,2,8.91,$$
243,18.78,3.00,Female,No,Thur,Dinner,2,9.39,$$

In [79]:
## Advanced Methods
# apply method with lamba function


def simple_square(num: float):
    return num**2

simple_square(16.99)

288.66009999999994

In [77]:
lambda num: num**2

In [78]:
df['total_bill'].apply(lambda num: num**2)

0      288.6601
1      106.9156
2      441.4201
3      560.7424
4      604.6681
         ...
239    842.7409
240    738.7524
241    513.9289
242    317.5524
243    352.6884
Name: total_bill, Length: 244, dtype: float64

In [80]:
def quality(total_bill, tip):
    if (tip/total_bill) > 0.25:
        return "Generous Tip! Thank you for visiting !"
    elif (tip/total_bill) == 0:
        return "No tip provided"

    else :
        return "others"

In [83]:
df['Tip_Quality'] = df[['total_bill','tip']].apply( lambda df:quality(df['total_bill'],df['tip']),axis =1)
df['Tip_Quality']

0      others
1      others
2      others
3      others
4      others
        ...
239    others
240    others
241    others
242    others
243    others
Name: Tip_Quality, Length: 244, dtype: str

In [86]:
df['Tip_Quality'].unique()

<StringArray>
['others', 'Generous Tip! Thank you for visiting !']
Length: 2, dtype: str

In [88]:
df[df['Tip_Quality'] == 'Generous Tip! Thank you for visiting !']

,total_bill,tip,sex,smoker,day,time,size,price_per_person,Expensive,Tip_Quality
51,10.29,2.60,Female,No,Sun,Dinner,2,5.14,$,Generous Tip! Thank you for visiting !
67,3.07,1.00,Female,Yes,Sat,Dinner,1,3.07,$,Generous Tip! Thank you for visiting !
93,16.32,4.30,Female,Yes,Fri,Dinner,2,8.16,$$,Generous Tip! Thank you for visiting !
109,14.31,4.00,Female,Yes,Sat,Dinner,2,7.16,$$,Generous Tip! Thank you for visiting !
149,7.51,2.00,Male,No,Thur,Lunch,2,3.76,$,Generous Tip! Thank you for visiting !
172,7.25,5.15,Male,Yes,Sun,Dinner,2,3.62,$,Generous Tip! Thank you for visiting !
178,9.60,4.00,Female,Yes,Sun,Dinner,2,4.80,$,Generous Tip! Thank you for visiting !
183,23.17,6.50,Male,Yes,Sun,Dinner,4,5.79,$$,Generous Tip! Thank you for visiting !
221,13.42,3.48,Female,Yes,Fri,Lunch,2,6.71,$$,Generous Tip! Thank you for visiting !
232,11.61,3.39,Male,No,Sat,Dinner,2,5.80,$,Generous Tip! Thank you for visiting !

In [93]:
# Correlation
df[['total_bill','tip']]

     total_bill   tip
0         16.99  1.01
1         10.34  1.66
2         21.01  3.50
3         23.68  3.31
4         24.59  3.61
..          ...   ...
239       29.03  5.92
240       27.18  2.00
241       22.67  2.00
242       17.82  1.75
243       18.78  3.00

[244 rows x 2 columns]

In [ ]:
# Correlation
df[['total_bill','tip']].corr()

            total_bill       tip
total_bill    1.000000  0.675734
tip           0.675734  1.000000

In [96]:
df[['total_bill','tip','size','price_per_person']].corr()

                  total_bill       tip      size  price_per_person
total_bill          1.000000  0.675734  0.598315          0.647554
tip                 0.675734  1.000000  0.489299          0.347405
size                0.598315  0.489299  1.000000         -0.175359
price_per_person    0.647554  0.347405 -0.175359          1.000000