In [1]:
import numpy as np
import pandas as pd

----
------
## Note! Typical comparisons should be avoided with Missing Values

* https://towardsdatascience.com/navigating-the-hell-of-nans-in-python-71b12558895b
* https://stackoverflow.com/questions/20320022/why-in-numpy-nan-nan-is-false-while-nan-in-nan-is-true

This is generally because the logic here is, since we don't know these values, we can't know if they are equal to each other.

In [2]:
df = pd.read_csv("D:\\CUDA_ENV\\Bleep_B1\\2_Data_Handling_Tools\\Data\\movie_scores.csv")
df

   first_name last_name   age  sex  pre_movie_score  post_movie_score
0         Tom     Hanks  63.0    m              8.0              10.0
1         NaN       NaN   NaN  NaN              NaN               NaN
2        Hugh   Jackman  51.0    m              NaN               NaN
3       Oprah   Winfrey  66.0    f              6.0               8.0
4        Emma     Stone  31.0    f              7.0               9.0
5        John       NaN  48.0    m              8.0               NaN
6    Amitabh    Bachhan  74.0    m              9.0               NaN
7     Shreya    Ghoshal  41.0    f              6.0               8.0
8   Robert D.   Jackman  47.0    m              9.0               7.0
9    Jennifer  Lawrence   NaN    f              7.0               9.0
10        NaN    Clarke  33.0    f              6.0               NaN
11      Virat     Kohli  40.0    m              6.0               9.0

In [3]:
type(np.nan)

float

In [4]:
pd.NA

In [5]:
pd.NaT

NaT

In [6]:
np.nan == np.nan

False

In [7]:
np.nan is [np.nan]

False

In [8]:
df

   first_name last_name   age  sex  pre_movie_score  post_movie_score
0         Tom     Hanks  63.0    m              8.0              10.0
1         NaN       NaN   NaN  NaN              NaN               NaN
2        Hugh   Jackman  51.0    m              NaN               NaN
3       Oprah   Winfrey  66.0    f              6.0               8.0
4        Emma     Stone  31.0    f              7.0               9.0
5        John       NaN  48.0    m              8.0               NaN
6    Amitabh    Bachhan  74.0    m              9.0               NaN
7     Shreya    Ghoshal  41.0    f              6.0               8.0
8   Robert D.   Jackman  47.0    m              9.0               7.0
9    Jennifer  Lawrence   NaN    f              7.0               9.0
10        NaN    Clarke  33.0    f              6.0               NaN
11      Virat     Kohli  40.0    m              6.0               9.0

In [9]:
df.drop(["post_movie_score"],axis=1)

   first_name last_name   age  sex  pre_movie_score
0         Tom     Hanks  63.0    m              8.0
1         NaN       NaN   NaN  NaN              NaN
2        Hugh   Jackman  51.0    m              NaN
3       Oprah   Winfrey  66.0    f              6.0
4        Emma     Stone  31.0    f              7.0
5        John       NaN  48.0    m              8.0
6    Amitabh    Bachhan  74.0    m              9.0
7     Shreya    Ghoshal  41.0    f              6.0
8   Robert D.   Jackman  47.0    m              9.0
9    Jennifer  Lawrence   NaN    f              7.0
10        NaN    Clarke  33.0    f              6.0
11      Virat     Kohli  40.0    m              6.0

In [10]:
df

   first_name last_name   age  sex  pre_movie_score  post_movie_score
0         Tom     Hanks  63.0    m              8.0              10.0
1         NaN       NaN   NaN  NaN              NaN               NaN
2        Hugh   Jackman  51.0    m              NaN               NaN
3       Oprah   Winfrey  66.0    f              6.0               8.0
4        Emma     Stone  31.0    f              7.0               9.0
5        John       NaN  48.0    m              8.0               NaN
6    Amitabh    Bachhan  74.0    m              9.0               NaN
7     Shreya    Ghoshal  41.0    f              6.0               8.0
8   Robert D.   Jackman  47.0    m              9.0               7.0
9    Jennifer  Lawrence   NaN    f              7.0               9.0
10        NaN    Clarke  33.0    f              6.0               NaN
11      Virat     Kohli  40.0    m              6.0               9.0

In [11]:
df.iloc[2]

first_name             Hugh
last_name           Jackman
age                    51.0
sex                       m
pre_movie_score         NaN
post_movie_score        NaN
Name: 2, dtype: object

In [12]:
help(df.drop)

Help on method drop in module pandas.core.frame:

drop(
    labels: IndexLabel | ListLike = None,
    *,
    axis: Axis = 0,
    index: IndexLabel | ListLike = None,
    columns: IndexLabel | ListLike = None,
    level: Level | None = None,
    inplace: bool = False,
    errors: IgnoreRaise = 'raise'
) -> DataFrame | None method of pandas.DataFrame instance
    Drop specified labels from rows or columns.

    Remove rows or columns by specifying label names and corresponding
    axis, or by directly specifying index or column names. When using a
    multi-index, labels on different levels can be removed by specifying
    the level. See the :ref:`user guide <advanced.shown_levels>`
    for more information about the now unused levels.

    Parameters
    ----------
    labels : single label or iterable of labels
        Index or column labels to drop. A tuple will be used as a single
        label and not treated as an iterable.
    axis : {0 or 'index', 1 or 'columns'}, default 0
        Whether to drop labels from the index (0 or 'index') or
        columns (1 or 'columns').
    index : single label or iterable of labels
        Alternative to specifying axis (``labels, axis=0``
        is equivalent to ``index=labels``).
    columns : single label or iterable of labels
        Alternative to specifying axis (``labels, axis=1``
        is equivalent to ``columns=labels``).
    level : int or level name, optional
        For MultiIndex, level from which the labels will be removed.
    inplace : bool, default False
        If False, return a copy. Otherwise, do operation
        in place and return None.
    errors : {'ignore', 'raise'}, default 'raise'
        If 'ignore', suppress error and only existing labels are
        dropped.

    Returns
    -------
    DataFrame or None
        Returns DataFrame or None DataFrame with the specified
        index or column labels removed or None if inplace=True.

    Raises
    ------
    KeyError
        If any of the labels is not found in the selected axis.

    See Also
    --------
    DataFrame.loc : Label-location based indexer for selection by label.
    DataFrame.dropna : Return DataFrame with labels on given axis omitted
        where (all or any) data are missing.
    DataFrame.drop_duplicates : Return DataFrame with duplicate rows
        removed, optionally only considering certain columns.
    Series.drop : Return Series with specified index labels removed.

    Examples
    --------
    >>> df = pd.DataFrame(np.arange(12).reshape(3, 4), columns=["A", "B", "C", "D"])
    >>> df
       A  B   C   D
    0  0  1   2   3
    1  4  5   6   7
    2  8  9  10  11

    Drop columns

    >>> df.drop(["B", "C"], axis=1)
       A   D
    0  0   3
    1  4   7
    2  8  11

    >>> df.drop(columns=["B", "C"])
       A   D
    0  0   3
    1  4   7
    2  8  11

    Drop a row by index

    >>> df.drop([0, 1])
       A  B   C   D
    2  8  9  10  11

    Drop columns and/or rows of MultiIndex DataFrame

    >>> midx = pd.MultiIndex(
    ...     levels=[["llama", "cow", "falcon"], ["speed", "weight", "length"]],
    ...     codes=[[0, 0, 0, 1, 1, 1, 2, 2, 2], [0, 1, 2, 0, 1, 2, 0, 1, 2]],
    ... )
    >>> df = pd.DataFrame(
    ...     index=midx,
    ...     columns=["big", "small"],
    ...     data=[
    ...         [45, 30],
    ...         [200, 100],
    ...         [1.5, 1],
    ...         [30, 20],
    ...         [250, 150],
    ...         [1.5, 0.8],
    ...         [320, 250],
    ...         [1, 0.8],
    ...         [0.3, 0.2],
    ...     ],
    ... )
    >>> df
                    big     small
    llama   speed   45.0    30.0
            weight  200.0   100.0
            length  1.5     1.0
    cow     speed   30.0    20.0
            weight  250.0   150.0
            length  1.5     0.8
    falcon  speed   320.0   250.0
            weight  1.0     0.8
            length  0.3     0.2

    Drop a specific index combination from the MultiIndex
    DataFrame, i.e., drop the combination ``'falcon'`` and
    ``'weight'``, which deletes only the corresponding row

    >>> df.drop(index=("falcon", "weight"))
                    big     small
    llama   speed   45.0    30.0
            weight  200.0   100.0
            length  1.5     1.0
    cow     speed   30.0    20.0
            weight  250.0   150.0
            length  1.5     0.8
    falcon  speed   320.0   250.0
            length  0.3     0.2

    >>> df.drop(index="cow", columns="small")
                    big
    llama   speed   45.0
            weight  200.0
            length  1.5
    falcon  speed   320.0
            weight  1.0
            length  0.3

    >>> df.drop(index="length", level=1)
                    big     small
    llama   speed   45.0    30.0
            weight  200.0   100.0
    cow     speed   30.0    20.0
            weight  250.0   150.0
    falcon  speed   320.0   250.0
            weight  1.0     0.8

In [13]:


df_copy = df.copy()
df_copy = df_copy.drop(1,axis=0)

In [14]:
df_copy

   first_name last_name   age sex  pre_movie_score  post_movie_score
0         Tom     Hanks  63.0   m              8.0              10.0
2        Hugh   Jackman  51.0   m              NaN               NaN
3       Oprah   Winfrey  66.0   f              6.0               8.0
4        Emma     Stone  31.0   f              7.0               9.0
5        John       NaN  48.0   m              8.0               NaN
6    Amitabh    Bachhan  74.0   m              9.0               NaN
7     Shreya    Ghoshal  41.0   f              6.0               8.0
8   Robert D.   Jackman  47.0   m              9.0               7.0
9    Jennifer  Lawrence   NaN   f              7.0               9.0
10        NaN    Clarke  33.0   f              6.0               NaN
11      Virat     Kohli  40.0   m              6.0               9.0

In [15]:
df

   first_name last_name   age  sex  pre_movie_score  post_movie_score
0         Tom     Hanks  63.0    m              8.0              10.0
1         NaN       NaN   NaN  NaN              NaN               NaN
2        Hugh   Jackman  51.0    m              NaN               NaN
3       Oprah   Winfrey  66.0    f              6.0               8.0
4        Emma     Stone  31.0    f              7.0               9.0
5        John       NaN  48.0    m              8.0               NaN
6    Amitabh    Bachhan  74.0    m              9.0               NaN
7     Shreya    Ghoshal  41.0    f              6.0               8.0
8   Robert D.   Jackman  47.0    m              9.0               7.0
9    Jennifer  Lawrence   NaN    f              7.0               9.0
10        NaN    Clarke  33.0    f              6.0               NaN
11      Virat     Kohli  40.0    m              6.0               9.0

In [16]:
df = df.drop(1,axis=0)
df

   first_name last_name   age sex  pre_movie_score  post_movie_score
0         Tom     Hanks  63.0   m              8.0              10.0
2        Hugh   Jackman  51.0   m              NaN               NaN
3       Oprah   Winfrey  66.0   f              6.0               8.0
4        Emma     Stone  31.0   f              7.0               9.0
5        John       NaN  48.0   m              8.0               NaN
6    Amitabh    Bachhan  74.0   m              9.0               NaN
7     Shreya    Ghoshal  41.0   f              6.0               8.0
8   Robert D.   Jackman  47.0   m              9.0               7.0
9    Jennifer  Lawrence   NaN   f              7.0               9.0
10        NaN    Clarke  33.0   f              6.0               NaN
11      Virat     Kohli  40.0   m              6.0               9.0

In [17]:
df.isnull()

    first_name  last_name    age    sex  pre_movie_score  post_movie_score
0        False      False  False  False            False             False
2        False      False  False  False             True              True
3        False      False  False  False            False             False
4        False      False  False  False            False             False
5        False       True  False  False            False              True
6        False      False  False  False            False              True
7        False      False  False  False            False             False
8        False      False  False  False            False             False
9        False      False   True  False            False             False
10        True      False  False  False            False              True
11       False      False  False  False            False             False

In [18]:
df.isna()

    first_name  last_name    age    sex  pre_movie_score  post_movie_score
0        False      False  False  False            False             False
2        False      False  False  False             True              True
3        False      False  False  False            False             False
4        False      False  False  False            False             False
5        False       True  False  False            False              True
6        False      False  False  False            False              True
7        False      False  False  False            False             False
8        False      False  False  False            False             False
9        False      False   True  False            False             False
10        True      False  False  False            False              True
11       False      False  False  False            False             False

In [19]:
df

   first_name last_name   age sex  pre_movie_score  post_movie_score
0         Tom     Hanks  63.0   m              8.0              10.0
2        Hugh   Jackman  51.0   m              NaN               NaN
3       Oprah   Winfrey  66.0   f              6.0               8.0
4        Emma     Stone  31.0   f              7.0               9.0
5        John       NaN  48.0   m              8.0               NaN
6    Amitabh    Bachhan  74.0   m              9.0               NaN
7     Shreya    Ghoshal  41.0   f              6.0               8.0
8   Robert D.   Jackman  47.0   m              9.0               7.0
9    Jennifer  Lawrence   NaN   f              7.0               9.0
10        NaN    Clarke  33.0   f              6.0               NaN
11      Virat     Kohli  40.0   m              6.0               9.0

# Fill NA method : df.fillna()

In [20]:
# fill every single NAN value 

help(df.fillna)

Help on method fillna in module pandas.core.generic:

fillna(
    value: Hashable | Mapping | Series | DataFrame,
    *,
    axis: Axis | None = None,
    inplace: bool = False,
    limit: int | None = None
) -> Self method of pandas.DataFrame instance
    Fill NA/NaN values with `value`.

    Parameters
    ----------
    value : scalar, dict, Series, or DataFrame
        Value to use to fill holes (e.g. 0), alternately a
        dict/Series/DataFrame of values specifying which value to use for
        each index (for a Series) or column (for a DataFrame).  Values not
        in the dict/Series/DataFrame will not be filled. This value cannot
        be a list.
    axis : {0 or 'index'} for Series, {0 or 'index', 1 or 'columns'} for DataFrame
        Axis along which to fill missing values. For `Series`
        this parameter is unused and defaults to 0.
    inplace : bool, default False
        If True, fill in-place. Note: this will modify any
        other views on this object (e.g., a no-copy slice for a column in a
        DataFrame).
    limit : int, default None
        This is the maximum number of entries along the entire axis
        where NaNs will be filled. Must be greater than 0 if not None.

    Returns
    -------
    Series/DataFrame
        Object with missing values filled.

    See Also
    --------
    ffill : Fill values by propagating the last valid observation to next valid.
    bfill : Fill values by using the next valid observation to fill the gap.
    interpolate : Fill NaN values using interpolation.
    reindex : Conform object to new index.
    asfreq : Convert TimeSeries to specified frequency.

    Notes
    -----
    For non-object dtype, ``value=None`` will use the NA value of the dtype.
    See more details in the :ref:`Filling missing data<missing_data.fillna>`
    section.

    Examples
    --------
    >>> df = pd.DataFrame(
    ...     [
    ...         [np.nan, 2, np.nan, 0],
    ...         [3, 4, np.nan, 1],
    ...         [np.nan, np.nan, np.nan, np.nan],
    ...         [np.nan, 3, np.nan, 4],
    ...     ],
    ...     columns=list("ABCD"),
    ... )
    >>> df
         A    B   C    D
    0  NaN  2.0 NaN  0.0
    1  3.0  4.0 NaN  1.0
    2  NaN  NaN NaN  NaN
    3  NaN  3.0 NaN  4.0

    Replace all NaN elements with 0s.

    >>> df.fillna(0)
         A    B    C    D
    0  0.0  2.0  0.0  0.0
    1  3.0  4.0  0.0  1.0
    2  0.0  0.0  0.0  0.0
    3  0.0  3.0  0.0  4.0

    Replace all NaN elements in column 'A', 'B', 'C', and 'D', with 0, 1,
    2, and 3 respectively.

    >>> values = {"A": 0, "B": 1, "C": 2, "D": 3}
    >>> df.fillna(value=values)
         A    B    C    D
    0  0.0  2.0  2.0  0.0
    1  3.0  4.0  2.0  1.0
    2  0.0  1.0  2.0  3.0
    3  0.0  3.0  2.0  4.0

    Only replace the first NaN element.

    >>> df.fillna(value=values, limit=1)
         A    B    C    D
    0  0.0  2.0  2.0  0.0
    1  3.0  4.0  NaN  1.0
    2  NaN  1.0  NaN  3.0
    3  NaN  3.0  NaN  4.0

    When filling using a DataFrame, replacement happens along
    the same column names and same indices

    >>> df2 = pd.DataFrame(np.zeros((4, 4)), columns=list("ABCE"))
    >>> df.fillna(df2)
         A    B    C    D
    0  0.0  2.0  0.0  0.0
    1  3.0  4.0  0.0  1.0
    2  0.0  0.0  0.0  NaN
    3  0.0  3.0  0.0  4.0

    Note that column D is not affected since it is not present in df2.

In [21]:
df

   first_name last_name   age sex  pre_movie_score  post_movie_score
0         Tom     Hanks  63.0   m              8.0              10.0
2        Hugh   Jackman  51.0   m              NaN               NaN
3       Oprah   Winfrey  66.0   f              6.0               8.0
4        Emma     Stone  31.0   f              7.0               9.0
5        John       NaN  48.0   m              8.0               NaN
6    Amitabh    Bachhan  74.0   m              9.0               NaN
7     Shreya    Ghoshal  41.0   f              6.0               8.0
8   Robert D.   Jackman  47.0   m              9.0               7.0
9    Jennifer  Lawrence   NaN   f              7.0               9.0
10        NaN    Clarke  33.0   f              6.0               NaN
11      Virat     Kohli  40.0   m              6.0               9.0

In [22]:
df = df.fillna("soome number")
df

,first_name,last_name,age,sex,pre_movie_score,post_movie_score
0,Tom,Hanks,63.0,m,8.0,10.0
2,Hugh,Jackman,51.0,m,soome number,soome number
3,Oprah,Winfrey,66.0,f,6.0,8.0
4,Emma,Stone,31.0,f,7.0,9.0
5,John,soome number,48.0,m,8.0,soome number
6,Amitabh,Bachhan,74.0,m,9.0,soome number
7,Shreya,Ghoshal,41.0,f,6.0,8.0
8,Robert D.,Jackman,47.0,m,9.0,7.0
9,Jennifer,Lawrence,soome number,f,7.0,9.0
10,soome number,Clarke,33.0,f,6.0,soome number
11,Virat,Kohli,40.0,m,6.0,9.0

In [23]:
df = pd.read_csv("D:\\CUDA_ENV\\Bleep_B1\\2_Data_Handling_Tools\\Data\\movie_scores.csv")

In [24]:

df

   first_name last_name   age  sex  pre_movie_score  post_movie_score
0         Tom     Hanks  63.0    m              8.0              10.0
1         NaN       NaN   NaN  NaN              NaN               NaN
2        Hugh   Jackman  51.0    m              NaN               NaN
3       Oprah   Winfrey  66.0    f              6.0               8.0
4        Emma     Stone  31.0    f              7.0               9.0
5        John       NaN  48.0    m              8.0               NaN
6    Amitabh    Bachhan  74.0    m              9.0               NaN
7     Shreya    Ghoshal  41.0    f              6.0               8.0
8   Robert D.   Jackman  47.0    m              9.0               7.0
9    Jennifer  Lawrence   NaN    f              7.0               9.0
10        NaN    Clarke  33.0    f              6.0               NaN
11      Virat     Kohli  40.0    m              6.0               9.0

In [25]:
df['first_name']

0           Tom
1           NaN
2          Hugh
3         Oprah
4          Emma
5          John
6      Amitabh
7       Shreya
8     Robert D.
9      Jennifer
10          NaN
11        Virat
Name: first_name, dtype: str

In [27]:
df['first_name'].fillna('ssoo')

0           Tom
1          ssoo
2          Hugh
3         Oprah
4          Emma
5          John
6      Amitabh
7       Shreya
8     Robert D.
9      Jennifer
10         ssoo
11        Virat
Name: first_name, dtype: str

In [28]:
df.columns

Index(['first_name', 'last_name', 'age', 'sex', 'pre_movie_score',
       'post_movie_score'],
      dtype='str')

In [37]:
mean_age_column = df['age'].mean()
mean_age_column

np.float64(49.4)

In [34]:
df['age']

0     63.0
1      NaN
2     51.0
3     66.0
4     31.0
5     48.0
6     74.0
7     41.0
8     47.0
9      NaN
10    33.0
11    40.0
Name: age, dtype: float64

In [35]:
df['age'].fillna(mean_age_column)

0     63.0
1     49.4
2     51.0
3     66.0
4     31.0
5     48.0
6     74.0
7     41.0
8     47.0
9     49.4
10    33.0
11    40.0
Name: age, dtype: float64

In [38]:
df['pre_movie_score']

0     8.0
1     NaN
2     NaN
3     6.0
4     7.0
5     8.0
6     9.0
7     6.0
8     9.0
9     7.0
10    6.0
11    6.0
Name: pre_movie_score, dtype: float64

In [39]:
df['pre_movie_score'].median()

np.float64(7.0)

In [40]:
df['pre_movie_score'].fillna(df['pre_movie_score'].median())

0     8.0
1     7.0
2     7.0
3     6.0
4     7.0
5     8.0
6     9.0
7     6.0
8     9.0
9     7.0
10    6.0
11    6.0
Name: pre_movie_score, dtype: float64

In [41]:
# Interpolation Methods

airline_tix = {'first':100,'business':np.nan,'economy-plus':50,'economy':30}

import pandas as pd

series = pd.Series(airline_tix)

In [42]:
series

first           100.0
business          NaN
economy-plus     50.0
economy          30.0
dtype: float64

In [ ]:
series.interpolate()

first           100.0
business         75.0
economy-plus     50.0
economy          30.0
dtype: float64

In [44]:
df = pd.DataFrame(series,columns=['Price'])

In [45]:
df

              Price
first         100.0
business        NaN
economy-plus   50.0
economy        30.0

In [49]:
# df = df.reset_index()
# df.interpolate(method='spline',order=2)

In [50]:
df

   level_0         index  Price
0        0         first  100.0
1        1      business    NaN
2        2  economy-plus   50.0
3        3       economy   30.0

In [51]:
df = pd.read_csv("D:\\CUDA_ENV\\Bleep_B1\\2_Data_Handling_Tools\\Data\\movie_scores.csv")

In [52]:
df

   first_name last_name   age  sex  pre_movie_score  post_movie_score
0         Tom     Hanks  63.0    m              8.0              10.0
1         NaN       NaN   NaN  NaN              NaN               NaN
2        Hugh   Jackman  51.0    m              NaN               NaN
3       Oprah   Winfrey  66.0    f              6.0               8.0
4        Emma     Stone  31.0    f              7.0               9.0
5        John       NaN  48.0    m              8.0               NaN
6    Amitabh    Bachhan  74.0    m              9.0               NaN
7     Shreya    Ghoshal  41.0    f              6.0               8.0
8   Robert D.   Jackman  47.0    m              9.0               7.0
9    Jennifer  Lawrence   NaN    f              7.0               9.0
10        NaN    Clarke  33.0    f              6.0               NaN
11      Virat     Kohli  40.0    m              6.0               9.0

In [57]:
df['first_name'][1]

nan

In [62]:
df['age'] > 60

0      True
1     False
2     False
3      True
4     False
5     False
6      True
7     False
8     False
9     False
10    False
11    False
Name: age, dtype: bool

In [63]:
df['pre_movie_score'] > 7

0      True
1     False
2     False
3     False
4     False
5      True
6      True
7     False
8      True
9     False
10    False
11    False
Name: pre_movie_score, dtype: bool

In [64]:
(df['age'] > 60 ) & (df['pre_movie_score'] > 7)

0      True
1     False
2     False
3     False
4     False
5     False
6      True
7     False
8     False
9     False
10    False
11    False
dtype: bool

In [71]:
new_df = df[(df['age'] > 30 ) & (df['pre_movie_score'] > 7)]

In [72]:
new_df

  first_name last_name   age sex  pre_movie_score  post_movie_score
0        Tom     Hanks  63.0   m              8.0              10.0
5       John       NaN  48.0   m              8.0               NaN
6   Amitabh    Bachhan  74.0   m              9.0               NaN
8  Robert D.   Jackman  47.0   m              9.0               7.0

In [73]:
new_df['post_movie_score'].fillna(new_df['post_movie_score'].mean())

0    10.0
5     8.5
6     8.5
8     7.0
Name: post_movie_score, dtype: float64

In [74]:
scale =  0.75 
new_df['post_movie_score'].fillna(scale * new_df['pre_movie_score'].mean())

0    10.000
5     6.375
6     6.375
8     7.000
Name: post_movie_score, dtype: float64